spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        min-idle: 10
        max-idle: 100
    password: 123
    database: 1
  datasource:
    url: jdbc:mysql://localhost:3306/local_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
